version: 0.2
phases:
  install:
    commands:
      - echo [+] installation started on `date`
      - npm install
  build:
    commands:
      - echo [+] Build started on `date`
      - echo "REACT_APP_GMAP_KEY=${google_map_key}" >> .env
      - npm run build
artifacts:
  files: '**/*'
  base-directory: build