name: "Terraform GitHub Actions CD"

on:
  push:
    branches:
      - master
      - staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{secrets.AWS_REGION_DEFAULT}}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_CLI_ARGS_init: '-backend-config="token=${{ secrets.TFE_TOKEN }}"'

    steps:
    - name: "Code Checkout"
      uses: actions/checkout@v1

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "init"

    - name: 'Terraform Plan Staging'
      if: github.ref == 'refs/heads/staging'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "plan"
      env:
        TF_WORKSPACE: "staging"

    - name: "Terraform Plan Production"
      if: github.ref == 'refs/heads/master'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "plan"
      env:
        TF_WORKSPACE: "production"

    - name: "Terraform Apply Staging"
      if: github.ref == 'refs/heads/staging'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "apply"
      env:
        TF_WORKSPACE: "staging"

    - name: "Terraform Apply Production"
      if: github.ref == 'refs/heads/master'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: "apply"
      env:
        TF_WORKSPACE: "production"
