name: "Terraform GitHub Actions CD"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_REGION: ${{secrets.AWS_REGION_DEFAULT}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_auth_password: ${{secrets.AUTH_PASSWORD}}
      TF_VAR_auth_username: ${{secrets.AUTH_USERNAME}}
      TF_VAR_cloudflare_api_token: ${{secrets.CLOUDFLARE_API_TOKEN}}
      TF_VAR_db_name: ${{secrets.DB_NAME}}
      TF_VAR_db_passwd: ${{secrets.DB_PASSWORD}}
      TF_VAR_db_username:  ${{secrets.DB_USERNAME}}
      TF_VAR_github_token: ${{secrets.GITHUB_TOKEN_ORG}}
      TF_VAR_hostname_api_default: ${{secrets.HOSTNAME_API_DEFAULT}}
      TF_VAR_hostname_app_front_default: ${{secrets.HOSTNAME_APP_FRONT_DEFAULT}}
      TF_VAR_jwt_secret_key: ${{secrets.JWT_SECRET_KEY}}
      TF_VAR_repository_name: "hummingbird-v2"
      TF_VAR_repository_owner: "CovidZero"
      TF_VERSION: "latest"
      TF_WORKING_DIR: "."
      INPUT_TF_ACTIONS_VERSION: 0.12.23

    steps:
    - name: "Code Checkout"
      uses: actions/checkout@v1

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "init"

    - name: "Terraform Apply Staging"
      if: github.ref == 'refs/heads/master'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "apply"