name: 'Terraform GitHub Actions CI'

on:
  - pull_request
  
env:
  tf_version: "latest"
  tf_working_dir: "."

jobs:
  ci:
    name: Test CI
    runs-on: ubuntu-latest

    env:
      TF_WORKSPACE: "production"
      TF_ACTIONS_VERSION: 0.12.23


    steps:
    - name: "Code Checkout"
      uses: actions/checkout@v1

    - name: "Terraform Check Indent"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "fmt"
        tf_actions_cli_credentials_token: ${{secrets.TERRAFORM_API_TOKEN}}

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "init"
        tf_actions_cli_credentials_token: ${{secrets.TERRAFORM_API_TOKEN}}

    - name: "Terraform Validate"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "validate"
        tf_actions_cli_credentials_token: ${{secrets.TERRAFORM_API_TOKEN}}

    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
        tf_actions_subcommand: "plan"
        tf_actions_cli_credentials_token: ${{secrets.TERRAFORM_API_TOKEN}}